import { Manrope } from 'next/font/google';
import { Toaster } from 'sonner';

import { NextAuthProvider } from '@/shared/components/layout';
import { ReactQueryProvider } from '@/shared/components/react-query';
import { cn } from '@/shared/utils/commons';
import '../styles/globals.css';

const manrope = Manrope({ weight: ['400', '500', '600', '700', '800'], subsets: ['latin'] });

export const metadata = {
  title: 'Asceoft',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(manrope.className, 'h-full')}>
        <Toaster position="top-right" richColors />
        <NextAuthProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
